id: I06324580
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T23:09:34+00:00'
last_modified: '2022-06-08T05:20:49.273979+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD19096
  title: མིང་གྲགས་མི་སྣ་གཞོན་དུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    979E:
      image_group_id: I2PD20282
      title: ''
      total_pages: 220
      order: 1
      base_file: 979E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
